### ISSUE TITLE
Host on NPM? / use npx

### ISSUE THREAD

**Issue by jasonbahl** [10up/project-scaffold#5]
Any chance this will end up being hosted on npmjs.com so we could use `npx` to run instead of installing globally?

**Comment by jasonbahl** [comment]
Also, fwiw, I used this yesterday to scaffold the OSHPD theme. Worked great. Thanks!!

**Comment by timwright12** [comment]
Yeah, it should be published after we've QA'd it to death. I'll keep this open and assign it to myself as a reminder.

**Comment by timwright12** [comment]
Closing this out: https://www.npmjs.com/package/@10up/create-10up
